version: '3.4'
networks:
  dev:
      driver: bridge
 
services:
  simple:
    image: docker.io/library/leavemanagementsystem
    depends_on:
       - "app_db"
    container_name: LeaveManagementSystemWebApi
    ports:
      - "8081:80"
    build:
      context: .
      dockerfile: Dockerfile
   
    environment:
       - ConnectionStrings__DefaultConnection=Server=app_db;Port=3306;Database=sampledb;Uid=root;Pwd=root
       - ASPNETCORE_URLS=http://+80
    networks:
       - dev
  app_db:
     image: mysql:latest
     container_name: app_db
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=sampledb
       
       - MYSQL_PASSWORD=root
     ports:
       - "6703:3306"
     restart: always
     volumes:
       - app_data:/var/lib/mysql
     networks:
      - dev
 
volumes:
  app_data: